/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BarberSettingsRouteImport } from './routes/barber.settings'
import { Route as BarberServicesRouteImport } from './routes/barber.services'
import { Route as BarberLoginRouteImport } from './routes/barber.login'
import { Route as BarberFinancialRouteImport } from './routes/barber.financial'
import { Route as BarberDashboardRouteImport } from './routes/barber.dashboard'
import { Route as BarberClientsRouteImport } from './routes/barber.clients'
import { Route as BarberAppointmentsRouteImport } from './routes/barber.appointments'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberSettingsRoute = BarberSettingsRouteImport.update({
  id: '/barber/settings',
  path: '/barber/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberServicesRoute = BarberServicesRouteImport.update({
  id: '/barber/services',
  path: '/barber/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberLoginRoute = BarberLoginRouteImport.update({
  id: '/barber/login',
  path: '/barber/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberFinancialRoute = BarberFinancialRouteImport.update({
  id: '/barber/financial',
  path: '/barber/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberDashboardRoute = BarberDashboardRouteImport.update({
  id: '/barber/dashboard',
  path: '/barber/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberClientsRoute = BarberClientsRouteImport.update({
  id: '/barber/clients',
  path: '/barber/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberAppointmentsRoute = BarberAppointmentsRouteImport.update({
  id: '/barber/appointments',
  path: '/barber/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/financial': typeof BarberFinancialRoute
  '/barber/login': typeof BarberLoginRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/financial': typeof BarberFinancialRoute
  '/barber/login': typeof BarberLoginRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/financial': typeof BarberFinancialRoute
  '/barber/login': typeof BarberLoginRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/reset-password'
    | '/servicos'
    | '/unsubscribe'
    | '/barber/appointments'
    | '/barber/clients'
    | '/barber/dashboard'
    | '/barber/financial'
    | '/barber/login'
    | '/barber/services'
    | '/barber/settings'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/reset-password'
    | '/servicos'
    | '/unsubscribe'
    | '/barber/appointments'
    | '/barber/clients'
    | '/barber/dashboard'
    | '/barber/financial'
    | '/barber/login'
    | '/barber/services'
    | '/barber/settings'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/reset-password'
    | '/servicos'
    | '/unsubscribe'
    | '/barber/appointments'
    | '/barber/clients'
    | '/barber/dashboard'
    | '/barber/financial'
    | '/barber/login'
    | '/barber/services'
    | '/barber/settings'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  ProdutosRoute: typeof ProdutosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicosRoute: typeof ServicosRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BarberAppointmentsRoute: typeof BarberAppointmentsRoute
  BarberClientsRoute: typeof BarberClientsRoute
  BarberDashboardRoute: typeof BarberDashboardRoute
  BarberFinancialRoute: typeof BarberFinancialRoute
  BarberLoginRoute: typeof BarberLoginRoute
  BarberServicesRoute: typeof BarberServicesRoute
  BarberSettingsRoute: typeof BarberSettingsRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/settings': {
      id: '/barber/settings'
      path: '/barber/settings'
      fullPath: '/barber/settings'
      preLoaderRoute: typeof BarberSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/services': {
      id: '/barber/services'
      path: '/barber/services'
      fullPath: '/barber/services'
      preLoaderRoute: typeof BarberServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/login': {
      id: '/barber/login'
      path: '/barber/login'
      fullPath: '/barber/login'
      preLoaderRoute: typeof BarberLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/financial': {
      id: '/barber/financial'
      path: '/barber/financial'
      fullPath: '/barber/financial'
      preLoaderRoute: typeof BarberFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/dashboard': {
      id: '/barber/dashboard'
      path: '/barber/dashboard'
      fullPath: '/barber/dashboard'
      preLoaderRoute: typeof BarberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/clients': {
      id: '/barber/clients'
      path: '/barber/clients'
      fullPath: '/barber/clients'
      preLoaderRoute: typeof BarberClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/appointments': {
      id: '/barber/appointments'
      path: '/barber/appointments'
      fullPath: '/barber/appointments'
      preLoaderRoute: typeof BarberAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  ProdutosRoute: ProdutosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicosRoute: ServicosRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BarberAppointmentsRoute: BarberAppointmentsRoute,
  BarberClientsRoute: BarberClientsRoute,
  BarberDashboardRoute: BarberDashboardRoute,
  BarberFinancialRoute: BarberFinancialRoute,
  BarberLoginRoute: BarberLoginRoute,
  BarberServicesRoute: BarberServicesRoute,
  BarberSettingsRoute: BarberSettingsRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
