/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarberSettingsRouteImport } from './routes/barber.settings'
import { Route as BarberServicesRouteImport } from './routes/barber.services'
import { Route as BarberLoginRouteImport } from './routes/barber.login'
import { Route as BarberFinancialRouteImport } from './routes/barber.financial'
import { Route as BarberDashboardRouteImport } from './routes/barber.dashboard'
import { Route as BarberClientsRouteImport } from './routes/barber.clients'
import { Route as BarberAppointmentsRouteImport } from './routes/barber.appointments'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberSettingsRoute = BarberSettingsRouteImport.update({
  id: '/barber/settings',
  path: '/barber/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberServicesRoute = BarberServicesRouteImport.update({
  id: '/barber/services',
  path: '/barber/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberLoginRoute = BarberLoginRouteImport.update({
  id: '/barber/login',
  path: '/barber/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberFinancialRoute = BarberFinancialRouteImport.update({
  id: '/barber/financial',
  path: '/barber/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberDashboardRoute = BarberDashboardRouteImport.update({
  id: '/barber/dashboard',
  path: '/barber/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberClientsRoute = BarberClientsRouteImport.update({
  id: '/barber/clients',
  path: '/barber/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberAppointmentsRoute = BarberAppointmentsRouteImport.update({
  id: '/barber/appointments',
  path: '/barber/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/financial': typeof BarberFinancialRoute
  '/barber/login': typeof BarberLoginRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/financial': typeof BarberFinancialRoute
  '/barber/login': typeof BarberLoginRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/financial': typeof BarberFinancialRoute
  '/barber/login': typeof BarberLoginRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/produtos'
    | '/reset-password'
    | '/servicos'
    | '/barber/appointments'
    | '/barber/clients'
    | '/barber/dashboard'
    | '/barber/financial'
    | '/barber/login'
    | '/barber/services'
    | '/barber/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/produtos'
    | '/reset-password'
    | '/servicos'
    | '/barber/appointments'
    | '/barber/clients'
    | '/barber/dashboard'
    | '/barber/financial'
    | '/barber/login'
    | '/barber/services'
    | '/barber/settings'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/produtos'
    | '/reset-password'
    | '/servicos'
    | '/barber/appointments'
    | '/barber/clients'
    | '/barber/dashboard'
    | '/barber/financial'
    | '/barber/login'
    | '/barber/services'
    | '/barber/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  ProdutosRoute: typeof ProdutosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicosRoute: typeof ServicosRoute
  BarberAppointmentsRoute: typeof BarberAppointmentsRoute
  BarberClientsRoute: typeof BarberClientsRoute
  BarberDashboardRoute: typeof BarberDashboardRoute
  BarberFinancialRoute: typeof BarberFinancialRoute
  BarberLoginRoute: typeof BarberLoginRoute
  BarberServicesRoute: typeof BarberServicesRoute
  BarberSettingsRoute: typeof BarberSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/settings': {
      id: '/barber/settings'
      path: '/barber/settings'
      fullPath: '/barber/settings'
      preLoaderRoute: typeof BarberSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/services': {
      id: '/barber/services'
      path: '/barber/services'
      fullPath: '/barber/services'
      preLoaderRoute: typeof BarberServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/login': {
      id: '/barber/login'
      path: '/barber/login'
      fullPath: '/barber/login'
      preLoaderRoute: typeof BarberLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/financial': {
      id: '/barber/financial'
      path: '/barber/financial'
      fullPath: '/barber/financial'
      preLoaderRoute: typeof BarberFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/dashboard': {
      id: '/barber/dashboard'
      path: '/barber/dashboard'
      fullPath: '/barber/dashboard'
      preLoaderRoute: typeof BarberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/clients': {
      id: '/barber/clients'
      path: '/barber/clients'
      fullPath: '/barber/clients'
      preLoaderRoute: typeof BarberClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/appointments': {
      id: '/barber/appointments'
      path: '/barber/appointments'
      fullPath: '/barber/appointments'
      preLoaderRoute: typeof BarberAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  ProdutosRoute: ProdutosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicosRoute: ServicosRoute,
  BarberAppointmentsRoute: BarberAppointmentsRoute,
  BarberClientsRoute: BarberClientsRoute,
  BarberDashboardRoute: BarberDashboardRoute,
  BarberFinancialRoute: BarberFinancialRoute,
  BarberLoginRoute: BarberLoginRoute,
  BarberServicesRoute: BarberServicesRoute,
  BarberSettingsRoute: BarberSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
