/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarberLoginRouteImport } from './routes/barber.login'
import { Route as BarberDashboardRouteImport } from './routes/barber.dashboard'
import { Route as BarberAppointmentsRouteImport } from './routes/barber.appointments'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberLoginRoute = BarberLoginRouteImport.update({
  id: '/barber/login',
  path: '/barber/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberDashboardRoute = BarberDashboardRouteImport.update({
  id: '/barber/dashboard',
  path: '/barber/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberAppointmentsRoute = BarberAppointmentsRouteImport.update({
  id: '/barber/appointments',
  path: '/barber/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/login': typeof BarberLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/login': typeof BarberLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/barber/appointments': typeof BarberAppointmentsRoute
  '/barber/dashboard': typeof BarberDashboardRoute
  '/barber/login': typeof BarberLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/contato'
    | '/produtos'
    | '/servicos'
    | '/barber/appointments'
    | '/barber/dashboard'
    | '/barber/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/contato'
    | '/produtos'
    | '/servicos'
    | '/barber/appointments'
    | '/barber/dashboard'
    | '/barber/login'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/contato'
    | '/produtos'
    | '/servicos'
    | '/barber/appointments'
    | '/barber/dashboard'
    | '/barber/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRoute
  ServicosRoute: typeof ServicosRoute
  BarberAppointmentsRoute: typeof BarberAppointmentsRoute
  BarberDashboardRoute: typeof BarberDashboardRoute
  BarberLoginRoute: typeof BarberLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/login': {
      id: '/barber/login'
      path: '/barber/login'
      fullPath: '/barber/login'
      preLoaderRoute: typeof BarberLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/dashboard': {
      id: '/barber/dashboard'
      path: '/barber/dashboard'
      fullPath: '/barber/dashboard'
      preLoaderRoute: typeof BarberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/appointments': {
      id: '/barber/appointments'
      path: '/barber/appointments'
      fullPath: '/barber/appointments'
      preLoaderRoute: typeof BarberAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRoute,
  ServicosRoute: ServicosRoute,
  BarberAppointmentsRoute: BarberAppointmentsRoute,
  BarberDashboardRoute: BarberDashboardRoute,
  BarberLoginRoute: BarberLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
